import type { ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { ComponentColorScope, COMPONENT_COLORWAYS, type ComponentColorwayId, type ComponentSurfaceMode } from "@/components/content/ComponentColorScope";
import { CalloutCard } from "@/components/content/CalloutCard";
import { OutboundLink } from "@/components/content/OutboundLink";
import { FactGrid } from "@/components/content/FactGrid";
import { FilterGroup } from "@/components/content/FilterGroup";
import { EmbedFrame } from "@/components/content/EmbedFrame";
import { EditorialQuote } from "@/components/content/EditorialQuote";
import { EmptyResultsMessage } from "@/components/content/EmptyResultsMessage";
import { DocumentCard } from "@/components/publications/DocumentCard";
import { ArchiveSearch } from "@/components/publications/ArchiveSearch";
import { TagFilter } from "@/components/publications/TagFilter";
import { CourseCard, ClubCard, CourseSubjectFilter } from "@/components/education/FractalUniversityPortal";
import { AudienceHighlight, MembershipButtonGroup } from "@/components/sections/Campus";
import { MandelbrotCorners } from "@/components/ui/MandelbrotCorners";
import { MandelbrotIcon } from "@/components/house/MandelbrotIcon";
import { PaperGrain } from "@/components/ui/PaperGrain";
import { FractalPattern } from "@/components/ui/FractalPattern";
import { FadeIn } from "@/components/ui/FadeIn";
import { PUBLICATION_DOCUMENTS } from "@/data/publications-documents";
import { FRACTALU_CATALOG } from "@/data/fractalu";
import { HOUSES } from "@/data/houses";

export const COMPONENT_CATEGORIES = ["Foundations & layout", "Actions & controls", "Cards & containers", "Media & decoration", "Brand & complex composites"] as const;
export type ComponentCategory = typeof COMPONENT_CATEGORIES[number];

export type ComponentSpecimenState = "default" | "long" | "missing" | "empty";
export interface ComponentSpecimenContext { colorway: ComponentColorwayId; surface: ComponentSurfaceMode; state: ComponentSpecimenState; content: string }
export interface ComponentRegistryEntry {
  id: string;
  name: string;
  componentName: string;
  category: ComponentCategory;
  sourcePath: string;
  purpose: string;
  useWhen: string;
  doNotUseWhen: string;
  contentFields: string[];
  variants: string[];
  themeable: boolean;
  surfaceModes: ComponentSurfaceMode[];
  accessibility: string;
  responsive: string;
  agentPhrase: string;
  keywords: string[];
  sampleContent?: string;
  previewStates?: readonly ComponentSpecimenState[];
  render?: (context: ComponentSpecimenContext) => ReactNode;
  referenceOnly?: string;
}

const reference = (
  id: string,
  name: string,
  componentName: string,
  category: ComponentCategory,
  sourcePath: string,
  purpose: string,
  keywords: string[] = [],
): ComponentRegistryEntry => ({
  id, name, componentName, category, sourcePath, purpose, keywords,
  useWhen: `Use ${name} when this established site pattern matches the content.`,
  doNotUseWhen: "Do not imitate it with page-local markup or force it into a context it does not own.",
  contentFields: ["See the typed source API"], variants: ["Production default"], themeable: false, surfaceModes: ["paper"],
  accessibility: "Preserve the component's documented semantics, labels, focus behavior, and reduced-motion behavior.",
  responsive: "Use in its intended page or viewport context; verify at 320px and 375px.",
  agentPhrase: `Use the **${name}** component.`,
  referenceOnly: "This component owns a page, viewport, animation, or media context that a small specimen would misrepresent. Open its source and production page.",
});

const sampleCourse = FRACTALU_CATALOG.courses[0];
const sampleClub = FRACTALU_CATALOG.clubs[0];
const campusPatternColor = HOUSES.find(({ id }) => id === "campus")!.palette.light;
const longText = "A deliberately long specimen demonstrates how this component wraps when an editor adds substantially more content than the default example.";

export const COMPONENT_REGISTRY: ComponentRegistryEntry[] = [
  {
    id: "color-pairing", name: "Color Pairing", componentName: "ComponentColorScope", category: "Foundations & layout", sourcePath: "src/components/content/ComponentColorScope.tsx",
    purpose: "Applies one approved token-backed identity and a safe text color to any themeable component.", useWhen: "Wrap a reusable card or control that needs a Fractal section identity.", doNotUseWhen: "Do not accept arbitrary hex values or use a house accent as essential text when its contrast is insufficient.",
    contentFields: ["colorway", "surface"], variants: COMPONENT_COLORWAYS.map(({ name }) => name), themeable: true, surfaceModes: ["paper", "light", "deep"],
    accessibility: "Every surface explicitly sets its on-surface text and focus variables.", responsive: "No layout behavior; scope follows its container.", agentPhrase: "Use the **Color Pairing** component with the requested approved token pair.", keywords: ["theme", "colour", "palette", "tokens"],
    sampleContent: "Approved color pairing", previewStates: ["default", "long"], render: ({ surface, content, state }) => <div className="library-color-grid">{COMPONENT_COLORWAYS.map((palette) => <ComponentColorScope key={palette.id} colorway={palette.id} surface={surface} className="rounded-md border p-4"><p className="text-label">{content}: {palette.name}</p><p className="text-body mt-2 opacity-80">{state === "long" ? `${palette.notes} ${longText}` : palette.notes}</p></ComponentColorScope>)}</div>,
  },
  reference("page-frame", "Page Frame", "page-gutter + max-width utilities", "Foundations & layout", "src/index.css", "Controls page width, safe-area gutters, and content measure.", ["container", "layout", "gutter"]),
  reference("type-style", "Type Style", "semantic type utilities", "Foundations & layout", "src/index.css", "Applies the named Display, Title, Subtitle, Body, Lead, Aside, Label, Mono-display, Input, or Button tier."),
  reference("reading-column", "Reading Column", "max-w-2xl / max-w-3xl", "Foundations & layout", "src/index.css", "Keeps prose at a readable measure inside a page frame."),
  reference("standard-section-frame", "Standard Section Frame", "page-gutter + section rhythm", "Foundations & layout", "src/index.css", "Owns standard section gutters and vertical rhythm."),
  reference("wide-card-grid", "Wide Card Grid", "intrinsic card grid", "Foundations & layout", "src/index.css", "Arranges repeatable cards with min-width-zero tracks and content-driven wrapping."),
  reference("section-header", "Section Header", "SectorHeader", "Foundations & layout", "src/components/layout/SectorHeader.tsx", "Identifies a house or editorial section with its letter and name."),
  reference("site-navigation", "Site Navigation", "Navbar", "Foundations & layout", "src/components/layout/Navbar.tsx", "Provides the viewport-owned site masthead and navigation."),
  reference("site-footer-marker", "Site Footer Marker", "Footer", "Foundations & layout", "src/components/layout/Footer.tsx", "Marks the page end and coordinates banner clearance."),
  { id: "content-card", name: "Content Card", componentName: "ContentCard", category: "Cards & containers", sourcePath: "src/components/content/ContentCard.tsx", purpose: "Provides the shared paper or accent card surface used by repeated content patterns.", useWhen: "Use as the structural shell beneath a specific content card.", doNotUseWhen: "Do not ship an unlabeled generic card when a named pattern already exists.", contentFields: ["semantic element", "surface", "content"], variants: ["Paper", "Accent"], themeable: true, surfaceModes: ["paper", "light", "deep"], accessibility: "Choose article or section semantics only when the content warrants them.", responsive: "Natural height; min-width-zero prevents grid overflow.", agentPhrase: "Use the **Content Card** shell for this new named pattern.", keywords: ["card shell", "container"], sampleContent: "Shared card shell", render: ({ content, state }) => <div className="rounded-lg border border-[var(--component-border)] bg-[var(--component-surface)] p-6"><p className="text-subtitle normal-case">{state === "empty" ? "Empty card" : content}</p>{state !== "empty" && <p className="text-body mt-2 opacity-75">{state === "long" ? longText : state === "missing" ? "Optional supporting copy omitted." : "A semantic content pattern supplies the actual fields."}</p>}</div> },
  {
    id: "action-buttons", name: "Action Button", componentName: "Button", category: "Actions & controls", sourcePath: "src/components/ui/button.tsx", purpose: "Provides the consistent primary, outline, quiet, and inline action treatments.", useWhen: "Use for actions or prominent destinations.", doNotUseWhen: "Do not use a button for passive information.", contentFields: ["label", "destination or action", "disabled"], variants: ["Primary", "Outline", "Quiet / Ghost", "Inline Button Link", "Disabled"], themeable: true, surfaceModes: ["paper", "light", "deep"], accessibility: "Uses native button/link semantics, 44px targets, and visible focus.", responsive: "Labels wrap only where the caller explicitly permits it.", agentPhrase: "Use the **Action Button** component and name its variant.", keywords: ["cta", "button container", "primary", "ghost", "outline"],
    sampleContent: "Primary action", previewStates: ["default", "long", "empty"], render: ({ content, state }) => <div className="flex flex-wrap gap-3"><Button>{state === "long" ? `${content} with a much longer descriptive label` : state === "empty" ? "" : content}</Button><Button variant="outline">Outline action</Button><Button variant="ghost">Quiet action</Button><Button variant="link">Inline link</Button><Button disabled>Disabled</Button></div>,
  },
  {
    id: "outbound-link", name: "Outbound Link", componentName: "OutboundLink", category: "Actions & controls", sourcePath: "src/components/content/OutboundLink.tsx", purpose: "Formats external, mail, and linked-title destinations with one diagonal-arrow grammar.", useWhen: "Use for links leaving the current content or for a linked card title.", doNotUseWhen: "Do not add a new-tab arrow to mail or same-context inline links.", contentFields: ["href", "label", "accessibleName"], variants: ["Inline", "Standalone", "Linked title", "Light/dark tone"], themeable: true, surfaceModes: ["paper", "deep"], accessibility: "HTTP links open safely in a new tab and announce that behavior when an accessible name is supplied.", responsive: "Long URLs and labels wrap anywhere.", agentPhrase: "Use the **Outbound Link** component.", keywords: ["external link", "outsource link", "arrow", "url"],
    sampleContent: "Visit Fractal", render: ({ content, state }) => <div className="flex flex-col items-start gap-3">{state !== "empty" && <OutboundLink href={state === "missing" ? "mailto:hello@fractal.nyc" : "https://fractal.nyc"} accessibleName={content}>{state === "long" ? `${content} — ${longText}` : content}</OutboundLink>}<p>Read the <OutboundLink href="https://fractal.nyc" variant="inline">external reference</OutboundLink>.</p><h3 className="text-subtitle"><OutboundLink href="https://fractal.nyc" variant="linked-title">Linked title</OutboundLink></h3></div>,
  },
  { id: "archive-search", name: "Archive Search Field", componentName: "ArchiveSearch", category: "Actions & controls", sourcePath: "src/components/publications/ArchiveSearch.tsx", purpose: "Searches titles, authors, and topics in the Library archive.", useWhen: "Use for archive keyword filtering.", doNotUseWhen: "Do not use as a general site search.", contentFields: ["value", "onChange"], variants: ["Empty", "Filled", "Focused", "Clearable"], themeable: false, surfaceModes: ["paper"], accessibility: "Native search field with an accessible clear control.", responsive: "Fills its available width.", agentPhrase: "Use the **Archive Search Field** component.", keywords: ["input", "find"], sampleContent: "community", previewStates: ["default", "long", "empty"], render: ({ content, state }) => <ArchiveSearch value={state === "empty" ? "" : state === "long" ? `${content} ${longText}` : content} onChange={() => undefined} /> },
  { id: "filter-chip", name: "Filter Chip", componentName: "FilterGroup / FilterChip", category: "Actions & controls", sourcePath: "src/components/content/FilterGroup.tsx", purpose: "Shows a labeled set of mutually selectable content filters.", useWhen: "Use to filter a visible collection by one category.", doNotUseWhen: "Do not use for navigation or multi-step forms.", contentFields: ["label", "options", "selected", "resultCount"], variants: ["Selected", "Unselected", "Empty results"], themeable: true, surfaceModes: ["paper"], accessibility: "Grouped buttons expose aria-pressed and announce result counts.", responsive: "Wraps without changing source order.", agentPhrase: "Use the **Filter Chip** and **Filter Group** components.", keywords: ["tag", "category", "subject", "results summary"], sampleContent: "Writing", render: ({ content, state }) => <FilterGroup label="Filter examples" options={["All", content || "Writing", "Movement"]} selected={state === "empty" ? "No results" : content || "Writing"} onChange={() => undefined} resultCount={state === "empty" ? 0 : 3} /> },
  reference("filter-results-summary", "Filter Results Summary", "FilterGroup live region", "Actions & controls", "src/components/content/FilterGroup.tsx", "Announces the current filtered result count without adding visual clutter."),
  { id: "empty-results-message", name: "Empty Results Message", componentName: "EmptyResultsMessage", category: "Actions & controls", sourcePath: "src/components/content/EmptyResultsMessage.tsx", purpose: "Explains that a filtered collection is empty and gives a recovery step.", useWhen: "Use when a search or filter produces no visible items.", doNotUseWhen: "Do not leave an empty collection unexplained.", contentFields: ["title", "recovery guidance"], variants: ["Search", "Subject filter"], themeable: true, surfaceModes: ["paper"], accessibility: "Place near the collection and pair dynamic changes with a live result summary.", responsive: "Centered copy wraps naturally.", agentPhrase: "Use the **Empty Results Message** component.", keywords: ["empty state", "zero results"], render: () => <EmptyResultsMessage /> },
  reference("icon-carousel-control", "Icon Button / Carousel Control", "MeetTheSpaceCarousel controls", "Actions & controls", "src/components/sections/MeetTheSpaceCarousel.tsx", "Provides labeled previous/next controls for the Campus carousel."),
  reference("archive-toolbar", "Archive Filter Group", "ArchiveToolbar", "Actions & controls", "src/components/publications/ArchiveToolbar.tsx", "Combines Library search, tags, and result summary."),
  { id: "library-tag-filter", name: "Library Tag Filter", componentName: "TagFilter", category: "Actions & controls", sourcePath: "src/components/publications/TagFilter.tsx", purpose: "Filters Library articles by one or more tags.", useWhen: "Use inside the Library archive toolbar.", doNotUseWhen: "Do not use as site navigation.", contentFields: ["tags", "counts", "active tags"], variants: ["Selected", "Unselected"], themeable: false, surfaceModes: ["paper"], accessibility: "Buttons expose pressed state and document counts.", responsive: "Scrolls horizontally on narrow screens and wraps on wider screens.", agentPhrase: "Use the **Library Tag Filter** component.", keywords: ["badge", "tag"], render: () => <TagFilter tags={["community", "education"]} tagCounts={new Map([["community", 8], ["education", 3]])} activeTags={new Set(["community"])} onToggle={() => undefined} /> },
  {
    id: "library-article-card", name: "Library Article Card", componentName: "DocumentCard", category: "Cards & containers", sourcePath: "src/components/publications/DocumentCard.tsx", purpose: "Presents one publication with category, title, byline, description, and destination.", useWhen: "Use for an item in the Library archive.", doNotUseWhen: "Do not use for courses, calls to action, or unlinked notes.", contentFields: ["category", "title", "byline", "description", "url"], variants: ["Full description", "Missing description", "Long title", "Hover/focus"], themeable: true, surfaceModes: ["paper"], accessibility: "The whole card is one external link with a visible focus ring.", responsive: "Fills its grid track; long content wraps.", agentPhrase: "Use the **Library Article Card** component.", keywords: ["article container", "library container", "publication", "document card"], sampleContent: PUBLICATION_DOCUMENTS[0].title, render: ({ colorway, content, state }) => <DocumentCard document={{ ...PUBLICATION_DOCUMENTS[0], title: state === "empty" ? "Untitled article" : state === "long" ? `${content}: ${longText}` : content, description: state === "missing" ? "" : state === "long" ? longText : PUBLICATION_DOCUMENTS[0].description }} colorway={colorway} />,
  },
  reference("library-article-grid", "Library Article Grid", "DocumentGrid", "Cards & containers", "src/components/publications/DocumentGrid.tsx", "Arranges Library article cards and owns the empty-results message.", ["empty state"]),
  {
    id: "note-callout", name: "Note / Callout Card", componentName: "CalloutCard", category: "Cards & containers", sourcePath: "src/components/content/CalloutCard.tsx", purpose: "Highlights a short note, invitation, instruction, or related action without becoming a full content card.", useWhen: "Use for notes such as Visiting NYC?, Curious about Fractal?, or Want to teach?.", doNotUseWhen: "Do not use for long articles or repeated catalog items.", contentFields: ["label", "prose", "links/actions", "corner size", "surface"], variants: ["Paper", "Tint", "With actions", "Long copy"], themeable: true, surfaceModes: ["paper", "light", "deep"], accessibility: "Associate the label with its containing section when it acts as a heading.", responsive: "Natural height and wrapping; no fixed width.", agentPhrase: "Use the **Note / Callout Card** component.", keywords: ["note container", "callout", "highlight", "info box"], sampleContent: "A useful note", render: ({ content, state }) => <CalloutCard label={content || "Untitled note"} actions={state === "missing" || state === "empty" ? undefined : <Button variant="outline">Optional action</Button>}>{state === "empty" ? "" : state === "long" ? longText : "Use this for a concise explanation that deserves a visible boundary."}</CalloutCard>,
  },
  { id: "course-card", name: "Course Card", componentName: "CourseCard", category: "Cards & containers", sourcePath: "src/components/education/FractalUniversityPortal.tsx", purpose: "Presents one class with instructors, description, facts, links, and optional media.", useWhen: "Use for a semester course in the Education catalog.", doNotUseWhen: "Do not manually rebuild this container when refreshing a semester.", contentFields: ["title", "category", "ordered instructors", "schedule", "dates", "location", "price", "description", "links", "video"], variants: ["Linked title", "Missing optional links", "Multiple instructors", "Long content"], themeable: true, surfaceModes: ["paper"], accessibility: "Instructor biographies support keyboard pin/Escape behavior in the catalog view.", responsive: "Uses inline biographies on touch/small screens and enhanced previews for fine pointers.", agentPhrase: "Use the **Course Card** component.", keywords: ["class container", "education course", "semester"], sampleContent: sampleCourse.title, render: ({ content, state }) => <CourseCard course={{ ...sampleCourse, title: content || "Untitled course", description: state === "empty" ? "" : state === "long" ? longText : sampleCourse.description, detailsUrl: state === "missing" ? undefined : sampleCourse.detailsUrl, detailsLabel: state === "missing" ? undefined : sampleCourse.detailsLabel, videoUrl: state === "missing" ? undefined : sampleCourse.videoUrl }} isFinePointer={false} pinnedInstructorId={null} suppressedInstructorId={null} setPinnedInstructorId={() => undefined} setSuppressedInstructorId={() => undefined} /> },
  { id: "course-fact-grid", name: "Course Fact Grid", componentName: "FactGrid", category: "Cards & containers", sourcePath: "src/components/content/FactGrid.tsx", purpose: "Pairs compact labels and values for schedule, dates, location, and price.", useWhen: "Use for two or more comparable metadata facts.", doNotUseWhen: "Do not use for narrative prose.", contentFields: ["label/value items"], variants: ["Two-column", "Long values", "Missing optional value"], themeable: true, surfaceModes: ["paper", "light", "deep"], accessibility: "Uses semantic dl/dt/dd markup.", responsive: "Values wrap within min-width-zero tracks.", agentPhrase: "Use the **Course Fact Grid** component.", keywords: ["facts", "metadata list"], render: () => <FactGrid items={[{ label: "Schedule", value: "Wednesdays, 7–8:30pm" }, { label: "Location", value: "Fractal Campus" }, { label: "Price", value: "$160 / $200" }, { label: "Dates", value: "Jun 17 – Jul 8" }]} /> },
  reference("metadata-facts-list", "Metadata / Facts List", "FactGrid", "Cards & containers", "src/components/content/FactGrid.tsx", "Presents general label/value metadata with semantic description-list markup."),
  reference("amenity-list", "Amenity List", "Campus amenities list", "Cards & containers", "src/components/sections/Campus.tsx", "Presents a concise, scannable set of Campus amenities."),
  reference("category-badge", "Category Badge", "TagFilter / card category label", "Cards & containers", "src/components/publications/TagFilter.tsx", "Labels or filters content by a short category or tag."),
  reference("photo-frame", "Photo Frame", "Campus photo frame", "Media & decoration", "src/components/sections/Campus.tsx", "Provides the bordered, cropped presentation for a single editorial photo."),
  { id: "club-card", name: "Club / Open Group Card", componentName: "ClubCard", category: "Cards & containers", sourcePath: "src/components/education/FractalUniversityPortal.tsx", purpose: "Presents a recurring Education club or open group.", useWhen: "Use for clubs and informal recurring programs.", doNotUseWhen: "Do not put a semester course into this smaller record shape.", contentFields: ["name", "description", "schedule", "location", "links"], variants: ["With details", "Action only", "Long copy"], themeable: true, surfaceModes: ["paper"], accessibility: "Links receive specific accessible names.", responsive: "Facts stack or split based on available width.", agentPhrase: "Use the **Club / Open Group Card** component.", keywords: ["club container", "open group"], sampleContent: sampleClub.name, render: ({ content, state }) => <ClubCard club={{ ...sampleClub, name: content || "Untitled club", description: state === "empty" ? "" : state === "long" ? longText : sampleClub.description, detailsUrl: state === "missing" ? undefined : sampleClub.detailsUrl, detailsLabel: state === "missing" ? undefined : sampleClub.detailsLabel }} /> },
  { id: "course-subject-filter", name: "Course Subject Filter", componentName: "CourseSubjectFilter", category: "Actions & controls", sourcePath: "src/components/education/FractalUniversityPortal.tsx", purpose: "Filters the real Education course collection by derived categories.", useWhen: "Use above an Education course catalog.", doNotUseWhen: "Do not hard-code categories separately from the catalog data.", contentFields: ["derived categories", "selection", "result count"], variants: ["All", "Selected", "New category", "Empty result"], themeable: true, surfaceModes: ["paper"], accessibility: "Pressed state and result announcement are exposed.", responsive: "Options wrap in source order.", agentPhrase: "Use the **Course Subject Filter** component.", keywords: ["class tags", "education filter"], render: () => <CourseSubjectFilter categories={["All", "Literature", "Writing"]} selected="All" onChange={() => undefined} resultCount={2} /> },
  { id: "campus-audience-highlight", name: "Campus Audience Highlight", componentName: "AudienceHighlight", category: "Cards & containers", sourcePath: "src/components/sections/Campus.tsx", purpose: "Highlights one of the Campus audiences with frosted branded action styling.", useWhen: "Use for a short numbered Campus audience destination.", doNotUseWhen: "Do not use as a generic article card.", contentFields: ["number", "title", "description", "optional link"], variants: ["Linked", "Static", "Hover/focus"], themeable: true, surfaceModes: ["paper", "light", "deep"], accessibility: "Linked cards use native anchor semantics and a full touch target.", responsive: "Fills its grid track and wraps long labels.", agentPhrase: "Use the **Campus Audience Highlight** component.", keywords: ["campus highlight container", "audience card"], sampleContent: "Accelerator participants", render: ({ content, state }) => <AudienceHighlight num="01" title={content || "Audience"} description={state === "empty" ? "" : state === "long" ? longText : "Students mastering practical AI in a six-week cohort."} href={state === "missing" ? null : "https://fractal.nyc"} /> },
  { id: "membership-button-group", name: "Membership Button Group", componentName: "MembershipButtonGroup", category: "Cards & containers", sourcePath: "src/components/sections/Campus.tsx", purpose: "Presents Campus full-time and part-time membership actions together.", useWhen: "Use for the canonical Campus membership choices.", doNotUseWhen: "Do not use for unrelated two-button groups.", contentFields: ["membership labels", "access", "price", "destinations"], variants: ["Stacked", "Side by side"], themeable: true, surfaceModes: ["deep"], accessibility: "Each option is a native link with a descriptive label.", responsive: "Stacks on mobile and becomes a row at the established breakpoint.", agentPhrase: "Use the **Membership Button Group** component.", keywords: ["campus buttons", "membership tiers"], render: () => <MembershipButtonGroup /> },
  { id: "embed-frame", name: "Embedded Content Frame", componentName: "EmbedFrame", category: "Media & decoration", sourcePath: "src/components/content/EmbedFrame.tsx", purpose: "Frames a trusted embedded calendar or similar external document.", useWhen: "Use for a titled, lazy-loaded iframe such as Events/Luma.", doNotUseWhen: "Do not embed arbitrary untrusted content.", contentFields: ["src", "title", "permissions", "height"], variants: ["Calendar", "Bounded preview"], themeable: true, surfaceModes: ["paper", "light"], accessibility: "Requires a meaningful iframe title.", responsive: "Owns full available width; caller owns intentional height.", agentPhrase: "Use the **Embedded Content Frame** component.", keywords: ["iframe", "luma"], render: () => <EmbedFrame title="Example embedded content" src="about:blank" className="h-48" /> },
  { id: "editorial-quote", name: "Editorial Quote", componentName: "EditorialQuote", category: "Cards & containers", sourcePath: "src/components/content/EditorialQuote.tsx", purpose: "Formats a substantial quotation with optional semantic citation.", useWhen: "Use for attributed editorial testimony.", doNotUseWhen: "Do not use for decorative pull text without a quotation.", contentFields: ["quote paragraphs", "citation"], variants: ["With citation", "Without citation"], themeable: true, surfaceModes: ["paper", "light", "deep"], accessibility: "Uses blockquote and footer semantics.", responsive: "Indent increases only when space permits.", agentPhrase: "Use the **Editorial Quote** component.", keywords: ["blockquote", "testimonial"], render: () => <EditorialQuote citation="Andrew Rose · Fractal Campus co-founder"><p>Our relationships here matter, and we conspire to push one another’s work forward.</p></EditorialQuote> },
  { id: "mandelbrot-corner-frame", name: "Mandelbrot Corner Frame", componentName: "MandelbrotCorners", category: "Media & decoration", sourcePath: "src/components/ui/MandelbrotCorners.tsx", purpose: "Adds inward-facing Mandelbrot corner marks around a container.", useWhen: "Use when a container has enough safe padding for the selected corner size.", doNotUseWhen: "Do not place corners over text or media controls.", contentFields: ["corner size", "opacity", "content"], variants: ["XS", "Small", "Medium", "Large"], themeable: true, surfaceModes: ["paper", "light", "deep"], accessibility: "Decorations are hidden from assistive technology.", responsive: "Padding must meet the documented safe-area invariant.", agentPhrase: "Use the **Mandelbrot Corner Frame** component.", keywords: ["corners", "container decoration"], render: () => <MandelbrotCorners size="sm" className="border p-12"><p>Framed content</p></MandelbrotCorners> },
  { id: "mandelbrot-icon", name: "Mandelbrot Icon", componentName: "MandelbrotIcon", category: "Media & decoration", sourcePath: "src/components/house/MandelbrotIcon.tsx", purpose: "Renders the small fractal brand glyph.", useWhen: "Use as non-essential brand decoration.", doNotUseWhen: "Do not use as an unlabeled interactive control.", contentFields: ["size", "opacity"], variants: ["Decorative sizes"], themeable: true, surfaceModes: ["paper", "light", "deep"], accessibility: "Keep decorative instances aria-hidden.", responsive: "Uses caller-provided intrinsic size.", agentPhrase: "Use the **Mandelbrot Icon** component.", keywords: ["brand glyph"], render: () => <MandelbrotIcon size={64} /> },
  { id: "paper-grain-overlay", name: "Paper Grain Overlay", componentName: "PaperGrain", category: "Media & decoration", sourcePath: "src/components/ui/PaperGrain.tsx", purpose: "Adds the subtle material texture used by frosted actions.", useWhen: "Use within a positioned branded surface.", doNotUseWhen: "Do not let it intercept input or reduce text contrast.", contentFields: ["none"], variants: ["Production texture"], themeable: false, surfaceModes: ["paper", "light", "deep"], accessibility: "Purely decorative and pointer-inert.", responsive: "Covers its positioned owner.", agentPhrase: "Use the **Paper Grain Overlay** component.", keywords: ["texture"], render: () => <div className="relative h-32 overflow-hidden rounded-md border"><PaperGrain /><p className="relative z-10 p-6">Textured surface</p></div> },
  { id: "fractal-pattern", name: "Fractal Pattern", componentName: "FractalPattern", category: "Media & decoration", sourcePath: "src/components/ui/FractalPattern.tsx", purpose: "Adds the subtle page-level fractal background pattern.", useWhen: "Use only on established house page surfaces.", doNotUseWhen: "Do not place in a small card.", contentFields: ["canonical color"], variants: ["House page"], themeable: false, surfaceModes: ["light", "deep"], accessibility: "Decorative and hidden from assistive technology.", responsive: "Viewport/page-owned.", agentPhrase: "Use the **Fractal Pattern** component.", keywords: ["background"], previewStates: ["default"], render: () => <div className="relative h-40 overflow-hidden rounded-md bg-house-campus-deep"><FractalPattern color={campusPatternColor} /></div> },
  { id: "fade-in", name: "Fade In", componentName: "FadeIn", category: "Media & decoration", sourcePath: "src/components/ui/FadeIn.tsx", purpose: "Reveals content with the site’s reduced-motion-aware entrance.", useWhen: "Use sparingly for meaningful section entrances.", doNotUseWhen: "Do not animate essential feedback or repeated workshop controls.", contentFields: ["delay", "children"], variants: ["Animated", "Reduced motion"], themeable: false, surfaceModes: ["paper"], accessibility: "Reduced-motion preference removes the transform/reveal motion.", responsive: "No layout ownership.", agentPhrase: "Use the **Fade In** component.", keywords: ["animation", "reveal"], render: () => <FadeIn><p className="text-subtitle">Reduced-motion-aware reveal</p></FadeIn> },
  reference("education-outbound-compat", "Education Outbound Link (compatibility)", "EducationOutboundLink", "Actions & controls", "src/components/education/EducationOutboundLink.tsx", "Keeps existing Education imports working while delegating to Outbound Link."),
  reference("gallery-image", "Gallery Image", "GalleryImage", "Media & decoration", "src/components/gallery/GalleryImage.tsx", "Renders a gallery image with its established loading and presentation behavior."),
  reference("photo-gallery", "Photo Gallery", "PhotoGallery", "Media & decoration", "src/components/gallery/PhotoGallery.tsx", "Arranges Story gallery sections and images."),
  reference("campus-banner", "Campus House Pennant", "CampusBannerSVG", "Brand & complex composites", "src/components/house/CampusBannerSVG.tsx", "Renders the Campus identity through Painted Relic Banner."),
  reference("co-living-banner", "Co-Living House Pennant", "CoLivingBannerSVG", "Brand & complex composites", "src/components/house/CoLivingBannerSVG.tsx", "Renders the Co-Living identity through Painted Relic Banner."),
  reference("education-banner", "Education House Pennant", "EducationBannerSVG", "Brand & complex composites", "src/components/house/EducationBannerSVG.tsx", "Renders the Education identity through Painted Relic Banner."),
  reference("events-banner", "Events House Pennant", "EventsBannerSVG", "Brand & complex composites", "src/components/house/EventsBannerSVG.tsx", "Renders the Events identity through Painted Relic Banner."),
  reference("library-banner", "Library House Pennant", "LibraryBannerSVG", "Brand & complex composites", "src/components/house/LibraryBannerSVG.tsx", "Renders the Library identity through Painted Relic Banner."),
  reference("political-club-banner", "Political Club House Pennant", "PoliticalClubBannerSVG", "Brand & complex composites", "src/components/house/PoliticalClubBannerSVG.tsx", "Renders the Political Club identity through Painted Relic Banner."),
  reference("painted-relic-banner", "House Pennant Renderer", "PaintedRelicBanner", "Brand & complex composites", "src/components/house/PaintedRelicBanner.tsx", "Shared renderer for all six painted house pennants."),
  reference("campus-section", "Campus Section", "Campus", "Brand & complex composites", "src/components/sections/Campus.tsx", "Composes the full Campus story, actions, audience highlights, quote, amenities, and carousel."),
  reference("hero-search", "Hero Search / Combobox", "Hero", "Brand & complex composites", "src/components/sections/Hero.tsx", "Provides the homepage hero and keyboard-accessible destination search.", ["combobox", "global search"]),
  reference("housing-map", "Housing Map", "HousingMap", "Brand & complex composites", "src/components/sections/HousingMap.tsx", "Shows the interactive Co-Living neighborhood map."),
  reference("meet-space-carousel", "Meet the Space Carousel", "MeetTheSpaceCarousel", "Brand & complex composites", "src/components/sections/MeetTheSpaceCarousel.tsx", "Shows Campus photos, captions, and carousel controls."),
  reference("origin-story", "Origin Story", "OriginStory", "Brand & complex composites", "src/components/sections/OriginStory.tsx", "Presents the long-form Fractal founding narrative."),
  reference("sierpinski-carpet", "Sierpinski Carpet", "SierpinskiCarpet", "Brand & complex composites", "src/components/sections/SierpinskiCarpet.tsx", "Renders the reduced-motion-aware recursive brand animation."),
  reference("fractal-city-scene", "Fractal City Scene", "FractalCityScene", "Brand & complex composites", "src/components/three/FractalCityScene.tsx", "Owns the homepage WebGL scene."),
  reference("octahedron-hero", "Octahedron Hero", "OctahedronHero", "Brand & complex composites", "src/components/three/OctahedronHero.tsx", "Renders the interactive house-navigation octahedron."),
];

export const searchableEntryText = (entry: ComponentRegistryEntry) => [entry.name, entry.componentName, entry.purpose, entry.agentPhrase, ...entry.keywords].join(" ").toLowerCase();
