/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Instructor = {
  _type: "instructor";
  name: string;
  bio: string;
};

export type FractalUClub = {
  _id: string;
  _type: "fractalUClub";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  semester: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "fractalUSemester";
  };
  key: string;
  name: string;
  description: string;
  schedule: string;
  location: string;
  detailsUrl?: string;
  detailsLabel?: string;
  actionUrl: string;
  actionLabel: string;
  displayOrder: number;
  visible: boolean;
};

export type FractalUCourse = {
  _id: string;
  _type: "fractalUCourse";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  semester: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "fractalUSemester";
  };
  key: string;
  title: string;
  category: string;
  instructors: Array<{
    _key: string;
  } & Instructor>;
  schedule: string;
  dates: string;
  location: string;
  price: string;
  description: string;
  detailsUrl?: string;
  detailsLabel?: string;
  applicationUrl: string;
  applicationLabel: string;
  videoUrl?: string;
  displayOrder: number;
  visible: boolean;
};

export type FractalUSemester = {
  _id: string;
  _type: "fractalUSemester";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key: string;
  semester: string;
  displayOrder: number;
  visible: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes = Instructor | FractalUClub | FractalUCourse | FractalUSemester | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/queries.ts
// Variable: FRACTALU_CATALOG_QUERY
// Query: *[_type == "fractalUSemester" && visible == true]    | order(displayOrder asc, key asc)[0] {      semester,      "courses": *[        _type == "fractalUCourse" &&        visible == true &&        references(^._id)      ] | order(displayOrder asc, key asc) {        "id": key,        title,        category,        instructors[]{name, bio},        schedule,        dates,        location,        price,        description,        detailsUrl,        detailsLabel,        applicationUrl,        applicationLabel,        videoUrl      },      "clubs": *[        _type == "fractalUClub" &&        visible == true &&        references(^._id)      ] | order(displayOrder asc, key asc) {        "id": key,        name,        description,        schedule,        location,        detailsUrl,        detailsLabel,        actionUrl,        actionLabel      }    }
export type FRACTALU_CATALOG_QUERYResult = {
  semester: string;
  courses: Array<{
    id: string;
    title: string;
    category: string;
    instructors: Array<{
      name: string;
      bio: string;
    }>;
    schedule: string;
    dates: string;
    location: string;
    price: string;
    description: string;
    detailsUrl: string | null;
    detailsLabel: string | null;
    applicationUrl: string;
    applicationLabel: string;
    videoUrl: string | null;
  }>;
  clubs: Array<{
    id: string;
    name: string;
    description: string;
    schedule: string;
    location: string;
    detailsUrl: string | null;
    detailsLabel: string | null;
    actionUrl: string;
    actionLabel: string;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"fractalUSemester\" && visible == true]\n    | order(displayOrder asc, key asc)[0] {\n      semester,\n      \"courses\": *[\n        _type == \"fractalUCourse\" &&\n        visible == true &&\n        references(^._id)\n      ] | order(displayOrder asc, key asc) {\n        \"id\": key,\n        title,\n        category,\n        instructors[]{name, bio},\n        schedule,\n        dates,\n        location,\n        price,\n        description,\n        detailsUrl,\n        detailsLabel,\n        applicationUrl,\n        applicationLabel,\n        videoUrl\n      },\n      \"clubs\": *[\n        _type == \"fractalUClub\" &&\n        visible == true &&\n        references(^._id)\n      ] | order(displayOrder asc, key asc) {\n        \"id\": key,\n        name,\n        description,\n        schedule,\n        location,\n        detailsUrl,\n        detailsLabel,\n        actionUrl,\n        actionLabel\n      }\n    }\n": FRACTALU_CATALOG_QUERYResult;
  }
}
